"""브로커 추상화.

Trader는 Broker 인터페이스(Protocol)에만 의존한다. 현재 구현체는 KisBroker 1개
(실전·모의투자 둘 다 base URL 차이로 처리). Phase 38.3에서 MockBroker 제거 —
KIS 자격증명 없는 자동 fallback이 사용자에게 "내가 모의투자 중인 줄 알았는데
사실 로컬 시뮬레이션이었다"는 신뢰 위험을 초래해서 명시적 에러로 전환.
"""

from __future__ import annotations

from typing import Protocol


class Broker(Protocol):
    def account_snapshot(self) -> dict: ...
    def price(self, symbol: str) -> float: ...
    def buy(self, symbol: str, qty: int) -> dict: ...
    def sell(self, symbol: str, qty: int) -> dict: ...
    def buy_limit(self, symbol: str, qty: int, limit_price: int) -> dict: ...
    def sell_limit(self, symbol: str, qty: int, limit_price: int) -> dict: ...
    def cancel(self, order_no: str, symbol: str, qty: int) -> dict: ...
    def order_status(self, order_no: str) -> dict: ...
    def pending_orders(self) -> list[dict]: ...
